name: Deploy React App
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
jobs: 
  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...